[mypy]
python_version = 3.10
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disallow_any_generics = False
warn_redundant_casts = True
warn_unused_ignores = True
check_untyped_defs = True
no_implicit_reexport = False

[mypy-pure_protobuf_rust]
ignore_missing_imports = True

[mypy-pytest]
ignore_missing_imports = True

[mypy-pytest_benchmark.*]
ignore_missing_imports = True

[mypy-tests.*]
disallow_untyped_defs = False
check_untyped_defs = False

# Strict checking for our Rust integration
[mypy-pure_protobuf.rust_integration]
disallow_untyped_defs = True
warn_return_any = True

[mypy-pure_protobuf._rust_backend]
disallow_untyped_defs = True
warn_return_any = True

